#################################
#####       Language        #####
#################################
#Language File
language: "language_en.yml"
#################################
#####      Permission       #####
#################################
#Permission to use command /clear
per_clear: "per.clear"
#################################
#####         TPS           #####
#################################
tps:
  checkInterval: 80         #detect interval,unit is second
  broadcast: true           #whether broadcast to server when tps change
  levels:                   #Note:tps is between 0.0 to 20.0.By default for example,17.5-20.0 tps is good,12.0-17.5 tps is fine,0.0-12.0 tps is bad
    good:
      threshold: 17.5
      status: "&aGood"
      show: "&2(Tip: Good tps!)"
    fine:
      threshold: 12.0
      status: "&6Fine"
      show: "&2(Tip: Fine tps!)"
    bad:
      status: "&cBad"
      show: "&2(Tip: Bad tps!)"
    unknown:                #it usually occur when server is just started
      status: "&7Unknown"
      show: "&2(Tip: unknown tps!)"
#################################
#####       Redstone        #####
#################################
redstone:
  ignoreWorlds:            #worlds don't detect(case sensitive)
    - 
  checkInterval: 100       #detect interval,unit is second
  gridSize: 20             #grid size
  drop: true               #true=block drop,false=block disappear
  removeBlocks:            #blocks need to be remove,Warning:Don't add the id of redtorch(It has bug)!
    - 55
  reset: false             #whether to reset the counter when a block is removed
  times:
    good:                  #When tps is good
      tipTimes: 90         #Max events per second,reach=broadcast
      removeTimes: 120     #Max events per second,reach=broadcast + remove(and reset the counter)
    fine:                  #When tps is fine
      tipTimes: 60
      removeTimes: 100
    bad:                   #When tps is bad
      tipTimes: 45
      removeTimes: 80
    unknown:               #When tps is unknown
      tipTimes: 90
      removeTimes: 120
  tip:
    ingame: false          #whether show in game
    ingameTipMinInterval: 5000 #min interval between two tips(to avoid spam,0 means no limit)
    console: true          #whether show in console
    consoleTipMinInterval: 500
#################################
#####         Crop          #####
#################################
#include the event of crop grow and mushroom spread
crop:
  ignoreWorlds:            #worlds don't detect(case sensitive)
    - 
  checkInterval: 20        #detect interval,unit is second
  gridSize: 30             #grid size
  max: 18                  #Max events in a Cycle
  drop: true               #true=block drop,false=block disappear
  reset: false             #whether to reset the counter when a block is removed
  tip:
    ingame: false
    ingameTipMinInterval: 5000
    console: true
    consoleTipMinInterval: 500
#################################
#####    自动与手动清理     #####
#################################
clear:
  ignoreWorlds:            #worlds don't detect(case sensitive)
    - 
  checkInterval: 300       #detect interval,unit is second
  startClearEntitys: 1000  #the threshold of the amount of entities to start auto-clear
  clear:
    good:                  #When tps is good,clear level:0
      show: "None"
      entity: false
      monster: false
      animal: false
    fine:                  #When tps is fine,clear level:1
      show: "Low"
      entity: true
      monster: true
      animal: false
    bad:                   #When tps is bad,clear level:2
      show: "High"
      entity: true
      monster: true
      animal: true
    unknown:               #When tps is unknown,clear level:3
      show: "None"
      entity: false
      monster: false
      animal: false
  entity:                  #Clear entities
    clear:                 #entities to clear(Warning:Don't add id 1)
      - 2
      - 10
      - 11
      - 12
      - 20
      - 22
    remainDropItems:       #the item-ids of drop-item,they won't be cleared(For example,A diamond is precious,so it shouldn't be cleared)
      - 256
      - 257
      - 258
      - 263
      - 264
      - 265
      - 266
      - 267
      - 276
      - 277
      - 278
      - 279
      - 283
      - 284
      - 285
      - 286
      - 292
      - 293
      - 298
      - 299
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308
      - 309
      - 310
      - 311
      - 312
      - 313
      - 314
      - 315
      - 316
      - 317
      - 319
      - 320
      - 322
      - 325
      - 326
      - 327
      - 328
      - 335
      - 340
      - 342
      - 343
      - 345
      - 347
      - 363
      - 364
      - 365
      - 366
      - 383
      - 384
      - 386
      - 387
      - 388
      - 396
      - 397
      - 399
      - 403
  monster:                   #Clear Monsters
    clear:                   #the entity-id of monsters that should be cleared
      - 50
      - 51
      - 52
      - 54
      - 57
      - 58
      - 59
      - 60
      - 61
      - 66
  animal:                    #Clear Animals
    gridSize: 30             #grid size
    maxPerGrid: 20           #Max amount in a grid
    animalEggChance: 40      #0-100,the chance of convert cleared animals to corresponding eggs 
    clearTypes:              #the entity-id of animals that should be cleared
      - 90
      - 91
      - 92
      - 93
    airBlocks:               #when check generate chest,these blocks will be regard as air
      - 0
      - 17
      - 18
      - 31
      - 32
      - 37
      - 38
      - 39
      - 40
      - 59
      - 83
      - 86
      - 106
      - 111